#!/usr/bin/env python3
"""
pr-gateway — Event-driven PR watcher daemon.

HTTP API (default :8645):
  POST   /watch                        Register a PR listener
  DELETE /watch/{repo}/{pr}            Remove all listeners for a PR
  DELETE /watch/{repo}/{pr}/{route}    Remove one specific listener
  GET    /watches                      List active listeners
  GET    /health                       Health check

Each registration specifies:
  - repo:     "owner/repo"
  - pr:       PR number, or 0 for a repo-level wildcard (source=webhook only)
  - route:    Hermes webhook route to call (e.g. "babysit-pr", "review-loop")
  - signals:  list of signals to forward, or ["*"] for all
              (PUSHED, OPENED, MERGED, CLOSED, DRAFT,
               CI_GREEN, CI_FAILED, CI_CANCELLED,
               NEW_COMMENTS, APPROVED, CHANGES_REQUESTED,
               REVIEW_REQUESTED, LABELED)
  - branch:   branch name (forwarded to agent)
  - worktree: local worktree path (forwarded to agent)
  - deliver:  Hermes delivery target (forwarded to agent)

The same PR can have multiple listeners with different routes/signals.
Registry key: "{repo}#{pr}@{route}"

Wildcard listeners (pr=0):
  Registered with source=webhook and pr=0, they receive events for ALL PRs on
  a repo. Useful for repo-level automation (e.g. review-loop) that should fire
  on any new push without knowing PR numbers in advance. Wildcard listeners are
  never auto-removed on MERGED/CLOSED (they survive across all PRs).

ETag state is shared across listeners for the same PR (one poll per PR,
dispatched to N listeners based on their signal filters).

Registry is persisted to REGISTRY_FILE for crash recovery.
"""

import hashlib
import hmac
import json
import logging
import os
import re
import sys
import threading
import time
from collections import defaultdict
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path
from typing import Optional
from urllib.error import HTTPError, URLError
from urllib.parse import urlparse, unquote
from urllib.request import Request, urlopen

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

SCRIPTS_DIR   = Path(__file__).parent
REGISTRY_FILE = SCRIPTS_DIR / "pr-gateway-registry.json"
GH_TOKEN_FILE = Path("/opt/data/.secrets/gh-token")
LOG_FILE      = SCRIPTS_DIR / "pr-gateway.log"
PID_FILE      = SCRIPTS_DIR / "pr-gateway.pid"

API_PORT      = int(os.environ.get("PR_GATEWAY_PORT", "8645"))       # internal only
GH_PORT       = int(os.environ.get("PR_GATEWAY_GH_PORT", "8646"))    # public, GitHub webhooks
TARGET_URL    = os.environ.get("PR_GATEWAY_TARGET_URL", "http://localhost:8644")
WEBHOOK_SECRET = os.environ.get("PR_GATEWAY_WEBHOOK_SECRET", "")
POLL_INTERVAL = int(os.environ.get("PR_GATEWAY_POLL_INTERVAL", "30"))
GITHUB_API    = "https://api.github.com"

ALL_SIGNALS   = {"PUSHED", "OPENED", "MERGED", "CLOSED", "DRAFT",
                 "CI_GREEN", "CI_FAILED", "CI_CANCELLED",
                 "NEW_COMMENTS", "APPROVED", "CHANGES_REQUESTED",
                 "REVIEW_REQUESTED", "LABELED"}

# Watermark present in every comment/review posted by the bot.
# Used to suppress NEW_COMMENTS signals triggered by our own output (anti-loop filter).
_BOT_WATERMARK = "generated by an AI agent, Herm\u00e8s"

# ---------------------------------------------------------------------------
# Event history — in-memory ring buffer (500 entries, never persisted)
# ---------------------------------------------------------------------------

import collections as _collections

_HISTORY_MAXLEN = 500
_history: _collections.deque = _collections.deque(maxlen=_HISTORY_MAXLEN)
_history_lock = threading.Lock()


def _record(kind: str, repo: str, pr: int, signal: str,
            route: str = "", result: str = "ok", detail: str = "") -> None:
    """Append one event to the in-memory history ring buffer."""
    entry = {
        "ts":     time.time(),
        "kind":   kind,    # webhook_received | poll_signal | dispatched | skipped | coalesced
        "repo":   repo,
        "pr":     pr,
        "signal": signal,
        "route":  route,
        "result": result,  # ok | skipped | error | coalesced | busy
        "detail": detail,
    }
    with _history_lock:
        _history.append(entry)


def _get_history() -> list[dict]:
    with _history_lock:
        return list(reversed(_history))  # newest first

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(LOG_FILE),
    ],
)
log = logging.getLogger("pr-gateway")

# ---------------------------------------------------------------------------
# Registry
#
# Two-level structure (both protected by _registry_lock):
#
#   _listeners: { "repo#pr@route": { listener fields + per-listener state } }
#   _pr_state:  { "repo#pr":       { shared ETag + GitHub state for the PR } }
#
# The poller iterates unique PRs (from _pr_state), detects signals, then fans
# out to all matching listeners in _listeners.
# ---------------------------------------------------------------------------

_registry_lock = threading.Lock()
_listeners: dict[str, dict] = {}
_pr_state:  dict[str, dict] = {}

# Coalesce + serialisation per listener.
#
# Two-layer design:
#   1. Coalesce (trailing-edge timer, 15s): absorbs GitHub per-check_run floods.
#      Latest-wins per signal type within the window.
#   2. Serialisation (per-listener queue): only one agent runs at a time per
#      listener. While running, incoming signals accumulate in a pending map
#      (latest-wins per signal type; PUSHED supersedes CI_GREEN, etc.).
#      When the agent finishes (or times out after _AGENT_TIMEOUT_S), the pending
#      map is flushed and the next batch dispatched.
#
# Signal cancellation on merge into pending:
#   PUSHED   supersedes CI_GREEN and CI_FAILED  (new commit invalidates CI state)
#   CI_GREEN supersedes CI_FAILED               (latest CI result wins)
#   CI_FAILED supersedes CI_GREEN               (latest CI result wins)
#   All other signal types are kept independently.

_COALESCE_WINDOW_S = 15    # seconds to wait after last identical signal before dispatch
_AGENT_TIMEOUT_S   = 600   # pessimistic max agent runtime; listener unlocked after this

_pending_lock = threading.Lock()

# key: lkey  →  {"timer":      Timer|None,          # active coalesce timer
#                 "coalesce":   dict[signal→float],  # signals accumulating in window
#                 "pending":    dict[signal→float],  # signals queued while agent runs
#                 "running":    bool,
#                 "run_started": float|None}         # time.time() when agent started
_listener_queues: dict[str, dict] = {}


def _lq(lkey: str) -> dict:
    """Return (creating if needed) the queue state for a listener key."""
    if lkey not in _listener_queues:
        _listener_queues[lkey] = {
            "timer":       None,
            "coalesce":    {},
            "pending":     {},
            "running":     False,
            "run_started": None,
        }
    return _listener_queues[lkey]


def _merge_signal(target: dict, signal: str) -> None:
    """Merge a signal into a pending/coalesce map applying cancellation rules."""
    if signal == "PUSHED":
        target.pop("CI_GREEN",  None)
        target.pop("CI_FAILED", None)
    elif signal in ("CI_GREEN", "CI_FAILED"):
        target.pop("CI_GREEN",  None)
        target.pop("CI_FAILED", None)
    target[signal] = time.time()


def _dispatch_pending(lkey: str, listener: dict) -> None:
    """Fire accumulated pending signals for a listener (must be called with _pending_lock held)."""
    q = _listener_queues.get(lkey)
    if not q or not q["pending"]:
        return
    signals_to_send = list(q["pending"].keys())
    q["pending"].clear()
    q["running"]     = True
    q["run_started"] = time.time()
    threading.Thread(
        target=_run_and_drain, args=(lkey, listener, signals_to_send),
        daemon=True, name=f"dispatch-{lkey}",
    ).start()


def _run_and_drain(lkey: str, listener: dict, signals: list[str]) -> None:
    """Send signals to Hermes then check if more are waiting (runs in its own thread)."""
    repo_pr = f"{listener['repo']}#{listener['pr']}"
    for sig in signals:
        log.info("Dispatching %s → %s [%s]", sig, repo_pr, listener["route"])
        ok = notify_target(listener, sig)
        _record("dispatched", listener["repo"], listener["pr"], sig,
                route=listener["route"],
                result="ok" if ok else "error")
    with _pending_lock:
        q = _lq(lkey)
        q["running"]     = False
        q["run_started"] = None
        if q["pending"]:
            _dispatch_pending(lkey, listener)


def _listener_key(repo: str, pr: int, route: str) -> str:
    return f"{repo}#{pr}@{route}"


def _pr_key(repo: str, pr: int) -> str:
    return f"{repo}#{pr}"


def _pr_has_poll_listeners(pr_key: str) -> bool:
    """Return True if at least one poll-sourced listener exists for this PR.

    Includes direct listeners on this PR AND repo-level wildcard (pr=0) poll
    listeners — wildcards rely on the poller discovering and tracking real PRs.
    """
    prefix = pr_key + "@"
    repo = pr_key.split("#")[0]
    wildcard_prefix = _pr_key(repo, 0) + "@"
    return any(
        (k.startswith(prefix) or k.startswith(wildcard_prefix))
        and _listeners[k].get("source", "poll") == "poll"
        for k in _listeners
    )


def _pr_has_direct_listeners(pr_key: str) -> bool:
    """Return True if at least one non-wildcard listener is registered for this PR."""
    prefix = pr_key + "@"
    return any(k.startswith(prefix) for k in _listeners)


def _repos_with_poll_wildcard() -> set[str]:
    """Return the set of repos that have a wildcard (pr=0) poll listener."""
    repos = set()
    with _registry_lock:
        for k, v in _listeners.items():
            if v.get("pr") == 0 and v.get("source", "poll") == "poll":
                repos.add(v["repo"])
    return repos


def _check_repo_changed(repo: str, etag: str | None) -> tuple[bool, str | None]:
    """ETag-conditional GET on the repo resource itself.

    Returns (changed, new_etag).
    - (False, None)      — 304, repo unchanged, skip PR list fetch
    - (True,  new_etag)  — 200, something changed, fetch PR list
    - (True,  None)      — error, fetch PR list to be safe
    """
    try:
        status, _, new_etag = gh_get(f"repos/{repo}", etag=etag)
        if status == 304:
            return False, None
        return True, new_etag
    except Exception as e:
        log.warning("Failed to check repo %s: %s", repo, e)
        return True, None  # err on the side of discovery


def _discover_open_prs(repo: str) -> list[int]:
    """Fetch the list of open PR numbers for a repo. Returns [] on error."""
    try:
        status, data, _ = gh_get(
            f"repos/{repo}/pulls?state=open&per_page=100",
        )
        if status in (200, 201) and isinstance(data, list):
            return [pr["number"] for pr in data if isinstance(pr, dict) and "number" in pr]
    except Exception as e:
        log.warning("Failed to discover PRs for %s: %s", repo, e)
    return []


def _pr_has_listeners(pr_key: str) -> bool:
    """Return True if at least one listener (any source) exists for this PR."""
    prefix = pr_key + "@"
    return any(k.startswith(prefix) for k in _listeners)


def load_registry() -> None:
    global _listeners, _pr_state
    if not REGISTRY_FILE.exists():
        return
    try:
        with open(REGISTRY_FILE) as f:
            data = json.load(f)
        with _registry_lock:
            _listeners = data.get("listeners", {})
            _pr_state  = data.get("pr_state", {})
        log.info("Loaded %d listener(s) for %d PR(s)",
                 len(_listeners), len(_pr_state))
    except Exception as e:
        log.error("Failed to load registry: %s", e)


def save_registry() -> None:
    tmp = REGISTRY_FILE.with_suffix(".tmp")
    try:
        with _registry_lock:
            data = {"listeners": dict(_listeners), "pr_state": dict(_pr_state)}
        with open(tmp, "w") as f:
            json.dump(data, f, indent=2)
        tmp.replace(REGISTRY_FILE)
    except Exception as e:
        log.error("Failed to save registry: %s", e)


def add_watch(entry: dict) -> tuple[bool, str]:
    repo  = entry.get("repo", "").strip()
    pr    = entry.get("pr")
    route = entry.get("route", "babysit-pr").strip()

    if not repo or pr is None:
        return False, "repo and pr are required"
    try:
        pr = int(pr)
    except (TypeError, ValueError):
        return False, "pr must be an integer"
    if pr < 0:
        return False, "pr must be a non-negative integer (0 = wildcard)"
    if not re.match(r"^[a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+$", repo):
        return False, "repo must be in owner/repo format"
    if not re.match(r"^[a-zA-Z0-9_-]+$", route):
        return False, "route must be alphanumeric/hyphens/underscores"

    raw_signals = entry.get("signals", ["*"])
    if raw_signals == ["*"] or "*" in raw_signals:
        signals = ["*"]
    else:
        invalid = set(raw_signals) - ALL_SIGNALS
        if invalid:
            return False, f"Unknown signals: {invalid}. Valid: {ALL_SIGNALS}"
        signals = list(raw_signals)

    # source: "poll" (default, apache/*) or "webhook" (maveniverse/*, jline/*)
    source = entry.get("source", "poll").strip()
    if source not in ("poll", "webhook"):
        return False, "source must be 'poll' or 'webhook'"

    # Wildcard (pr=0) with source=poll: the poller will discover open PRs for this
    # repo and poll them individually. source=webhook is still recommended when
    # admin access is available (lower latency, zero polling cost).
    # No validation error — both combinations are supported.

    lkey  = _listener_key(repo, pr, route)
    prkey = _pr_key(repo, pr)
    now   = time.time()

    listener = {
        "repo":     repo,
        "pr":       pr,
        "route":    route,
        "signals":  signals,
        "source":   source,
        "branch":   entry.get("branch", ""),
        "worktree": entry.get("worktree", ""),
        "deliver":  entry.get("deliver", "origin"),
        "added_at": now,
        # per-listener state
        "_last_signal": None,
        "_last_fired":  None,
    }

    with _registry_lock:
        existed = lkey in _listeners
        _listeners[lkey] = listener
        # Initialise PR state for non-wildcard listeners only
        # (wildcards have no per-PR state — they piggyback on webhook dispatch)
        if pr != 0 and prkey not in _pr_state:
            _pr_state[prkey] = {
                "repo":        repo,
                "pr":          pr,
                "_etag":       None,
                "_head_sha":   None,
                "_ci_status":  None,
                "_updated_at": None,
                "_last_polled": None,
            }

    save_registry()
    action = "Updated" if existed else "Registered"
    sig_desc = "*" if signals == ["*"] else ",".join(signals)
    pr_desc  = "wildcard" if pr == 0 else str(pr)
    log.info("%s listener: %s (pr=%s, signals=%s)", action, lkey, pr_desc, sig_desc)
    return True, f"{action} listener {lkey} (signals={sig_desc})"


def remove_watch(repo: str, pr: int, route: Optional[str] = None) -> tuple[bool, str]:
    """
    Remove listener(s). If route is given, remove only that listener.
    Otherwise remove all listeners for the PR (and its PR state).
    """
    prkey = _pr_key(repo, pr)

    with _registry_lock:
        if route:
            lkey = _listener_key(repo, pr, route)
            if lkey not in _listeners:
                return False, f"No listener found for {lkey}"
            del _listeners[lkey]
            # Clean up PR state if no listeners remain
            if not _pr_has_listeners(prkey):
                _pr_state.pop(prkey, None)
            removed = [lkey]
        else:
            # Remove all listeners for this PR
            to_remove = [k for k in _listeners if k.startswith(prkey + "@")]
            if not to_remove:
                return False, f"No listeners found for {prkey}"
            for k in to_remove:
                del _listeners[k]
            _pr_state.pop(prkey, None)
            removed = to_remove

    save_registry()
    for k in removed:
        log.info("Removed listener: %s", k)
    return True, f"Removed {len(removed)} listener(s): {', '.join(removed)}"


def list_watches() -> list[dict]:
    with _registry_lock:
        return [
            {k: v for k, v in entry.items() if not k.startswith("_")}
            for entry in _listeners.values()
        ]


def _get_pr_state_snapshot() -> dict[str, dict]:
    """Return a copy of pr_state for the poller."""
    with _registry_lock:
        return {k: dict(v) for k, v in _pr_state.items()}


def _get_listeners_for_pr(prkey: str) -> list[dict]:
    """Return copies of all listeners for a given PR key, plus repo-level wildcards (pr=0)."""
    # Extract repo from "repo#pr" key
    repo = prkey.split("#")[0]
    wildcard_prefix = _pr_key(repo, 0) + "@"
    with _registry_lock:
        return [
            dict(v) for k, v in _listeners.items()
            if k.startswith(prkey + "@") or k.startswith(wildcard_prefix)
        ]


def _update_pr_state(prkey: str, **kwargs) -> None:
    with _registry_lock:
        if prkey in _pr_state:
            _pr_state[prkey].update(kwargs)


def _update_listener_state(lkey: str, **kwargs) -> None:
    with _registry_lock:
        if lkey in _listeners:
            _listeners[lkey].update(kwargs)


# ---------------------------------------------------------------------------
# GitHub API helpers
# ---------------------------------------------------------------------------

def gh_token() -> str:
    if GH_TOKEN_FILE.exists():
        return GH_TOKEN_FILE.read_text().strip()
    return os.environ.get("GH_TOKEN", "")


def gh_get(path: str, etag: Optional[str] = None) -> tuple[int, dict | list | None, str | None]:
    url = f"{GITHUB_API}/{path.lstrip('/')}"
    headers = {
        "Authorization":        f"token {gh_token()}",
        "Accept":               "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if etag:
        headers["If-None-Match"] = etag
    try:
        req = Request(url, headers=headers)
        with urlopen(req, timeout=20) as resp:
            new_etag = resp.headers.get("ETag")
            body = json.loads(resp.read().decode())
            return resp.status, body, new_etag
    except HTTPError as e:
        if e.code == 304:
            return 304, None, None
        log.warning("GitHub API %s → %d", path, e.code)
        return e.code, None, None
    except (URLError, Exception) as e:
        log.warning("GitHub API %s → %s", path, e)
        return 0, None, None


def get_pr_snapshot(repo: str, pr: int) -> Optional[dict]:
    status, body, _ = gh_get(f"repos/{repo}/pulls/{pr}")
    if status == 200 and body:
        return {
            "state":      body.get("state"),
            "merged":     body.get("merged", False),
            "draft":      body.get("draft", False),
            "head_sha":   body.get("head", {}).get("sha"),
            "updated_at": body.get("updated_at"),
        }
    return None


def get_ci_status(repo: str, sha: str) -> str:
    status, body, _ = gh_get(f"repos/{repo}/commits/{sha}/check-runs")
    if status == 200 and body:
        runs = body.get("check_runs", [])
        if not runs:
            return "no_checks"
        conclusions = [r.get("conclusion") or "pending" for r in runs]
        if any(c == "failure" for c in conclusions):
            return "failure"
        if all(c == "success" for c in conclusions):
            return "success"
        return "pending"
    # Fallback: commit statuses
    status, body, _ = gh_get(f"repos/{repo}/commits/{sha}/status")
    if status == 200 and body:
        return body.get("state", "unknown")
    return "unknown"


# ---------------------------------------------------------------------------
# Hermes webhook callback
# ---------------------------------------------------------------------------

def _hmac_signature(secret: str, body: bytes) -> str:
    return "sha256=" + hmac.new(secret.encode(), body, hashlib.sha256).hexdigest()


def notify_target(listener: dict, signal: str) -> bool:
    """POST a signal to the Hermes webhook adapter for a specific route."""
    # Parse deliver field: "slack:C0BUUAYDQA1" → deliver_chat_id="C0BUUAYDQA1"
    # For Hermes webhook routes, deliver/deliver_extra are now handled natively in config.yaml.
    # We pass deliver_chat_id so the {deliver_chat_id} template in deliver_extra resolves correctly.
    raw_deliver = listener.get("deliver", "origin")
    if ":" in raw_deliver:
        _, deliver_chat_id = raw_deliver.split(":", 1)
    else:
        deliver_chat_id = raw_deliver

    payload = {
        "source":         "pr-gateway",
        "signal":         signal,
        "repo":           listener["repo"],
        "pr":             listener["pr"],
        "branch":         listener.get("branch", ""),
        "worktree":       listener.get("worktree", ""),
        "deliver_chat_id": deliver_chat_id,
    }
    body = json.dumps(payload).encode()
    sig  = _hmac_signature(WEBHOOK_SECRET, body)
    route = listener["route"]
    url  = f"{TARGET_URL}/webhooks/{route}"

    try:
        req = Request(
            url,
            data=body,
            headers={
                "Content-Type":        "application/json",
                "X-Hub-Signature-256": sig,
                "X-GitHub-Event":      "pr_gateway",
            },
            method="POST",
        )
        with urlopen(req, timeout=10) as resp:
            log.info("Dispatched [%s]: %s#%s → %s (HTTP %d)",
                     route, listener["repo"], listener["pr"], signal, resp.status)
            return True
    except Exception as e:
        log.error("Failed to dispatch [%s] for %s#%s: %s",
                  route, listener["repo"], listener["pr"], e)
        return False


# ---------------------------------------------------------------------------
# Poller
# ---------------------------------------------------------------------------

def _signals_match(listener: dict, signal: str) -> bool:
    sigs = listener.get("signals", ["*"])
    return "*" in sigs or signal in sigs


def _poll_pr(prkey: str, state: dict) -> list[str]:
    """
    Poll one PR. Returns the list of signals detected (may be empty).
    Updates _pr_state in place (via _update_pr_state).
    """
    repo = state["repo"]
    pr   = state["pr"]

    # ETag-conditional poll on timeline (304 = free)
    status, _, new_etag = gh_get(
        f"repos/{repo}/issues/{pr}/timeline?per_page=5",
        etag=state.get("_etag"),
    )
    if new_etag:
        _update_pr_state(prkey, _etag=new_etag, _last_polled=time.time())

    if status == 304:
        return []  # nothing changed

    if status not in (200, 201):
        log.warning("Unexpected status %d polling %s", status, prkey)
        return []

    # Something changed — fetch full PR state
    snapshot = get_pr_snapshot(repo, pr)
    if not snapshot:
        log.warning("Could not fetch PR snapshot for %s", prkey)
        return []

    prev_sha     = state.get("_head_sha")
    prev_ci      = state.get("_ci_status")
    prev_updated = state.get("_updated_at")
    cur_sha      = snapshot["head_sha"]
    cur_updated  = snapshot["updated_at"]

    # First time seeing this PR — initialise, emit nothing
    if prev_sha is None:
        cur_ci = get_ci_status(repo, cur_sha)
        _update_pr_state(prkey,
            _head_sha=cur_sha, _ci_status=cur_ci, _updated_at=cur_updated)
        log.info("Initialised state for %s (sha=%.8s, ci=%s)", prkey, cur_sha, cur_ci)
        return []

    signals = []

    if snapshot["merged"]:
        signals.append("MERGED")
    elif snapshot["state"] == "closed":
        signals.append("CLOSED")
    else:
        if cur_sha != prev_sha:
            signals.append("PUSHED")

        cur_ci = get_ci_status(repo, cur_sha)
        if cur_ci == "failure" and prev_ci != "failure":
            signals.append("CI_FAILED")
        elif cur_ci == "success" and (prev_ci != "success" or cur_sha != prev_sha):
            signals.append("CI_GREEN")

        if prev_updated and cur_updated != prev_updated and cur_sha == prev_sha:
            signals.append("NEW_COMMENTS")

        _update_pr_state(prkey,
            _head_sha=cur_sha, _ci_status=cur_ci, _updated_at=cur_updated)

    return signals


def _dispatch_signals(prkey: str, signals: list[str]) -> None:
    """Fan out detected signals to all matching listeners for this PR."""
    if not signals:
        return

    # Extract real PR number from prkey for passing to wildcard listeners
    repo, pr_str = prkey.split("#")
    real_pr = int(pr_str)

    listeners = _get_listeners_for_pr(prkey)
    terminal  = any(s in ("MERGED", "CLOSED") for s in signals)

    for listener in listeners:
        is_wildcard = listener["pr"] == 0
        route = listener["route"]
        lkey  = _listener_key(listener["repo"], listener["pr"], route)

        # Find the first signal this listener cares about
        matched = next((s for s in signals if _signals_match(listener, s)), None)
        if not matched:
            continue

        # For wildcard listeners, inject the real PR number so the agent knows which PR fired
        effective_listener = listener
        if is_wildcard:
            effective_listener = dict(listener)
            effective_listener["pr"] = real_pr

        # Record that this listener received the signal (entering coalesce window)
        _record("coalesced", listener["repo"], effective_listener["pr"], matched,
                route=route, result="coalescing",
                detail=f"window={_COALESCE_WINDOW_S}s")

        # --- Layer 1: coalesce trailing-edge timer ---
        # Re-arm the timer on every incoming signal of the same type.
        # When it expires quietly (no duplicate within _COALESCE_WINDOW_S),
        # we promote the coalesced signals to the serialisation layer.
        with _pending_lock:
            q = _lq(lkey)

            # Merge into coalesce window (latest-wins + cancellation rules)
            _merge_signal(q["coalesce"], matched)

            # Cancel existing timer and re-arm
            if q["timer"] is not None:
                q["timer"].cancel()

            def _coalesce_expired(k=lkey, lst=effective_listener):
                with _pending_lock:
                    q2 = _lq(k)
                    q2["timer"] = None
                    if not q2["coalesce"]:
                        return

                    # Check timeout: if running but agent has exceeded _AGENT_TIMEOUT_S, unlock
                    if q2["running"] and q2["run_started"] is not None:
                        if time.time() - q2["run_started"] > _AGENT_TIMEOUT_S:
                            log.warning("Agent timeout for %s — unlocking listener", k)
                            q2["running"]     = False
                            q2["run_started"] = None

                    # Merge coalesced signals into pending (with cancellation rules)
                    for sig in q2["coalesce"]:
                        _merge_signal(q2["pending"], sig)
                    q2["coalesce"].clear()

                    # --- Layer 2: serialisation ---
                    if not q2["running"]:
                        _dispatch_pending(k, lst)
                    else:
                        log.debug("Agent busy for %s — %d signal(s) queued: %s",
                                  k, len(q2["pending"]), list(q2["pending"]))
                        for sig in q2["pending"]:
                            _record("skipped", lst["repo"], lst["pr"], sig,
                                    route=lst["route"], result="busy",
                                    detail="agent running, signal queued")

            t = threading.Timer(_COALESCE_WINDOW_S, _coalesce_expired)
            t.daemon = True
            q["timer"] = t
            t.start()

    # Terminal signals — remove non-wildcard listeners for this PR only
    if terminal:
        remove_watch(repo, real_pr)


def poller_loop() -> None:
    log.info("Poller started (interval=%ds)", POLL_INTERVAL)
    # Per-repo discovery state: {repo: {"ts": float, "etag": str|None}}
    _repo_disc: dict[str, dict] = {}
    DISCOVERY_INTERVAL = 120  # check repo ETag every 2 minutes

    while True:
        # --- Repo-level discovery for poll wildcards ---
        # Gate: ETag-conditional GET on the repo itself (1 cheap call per repo).
        # Only fetch the open PR list when the repo ETag changes (200 vs 304).
        poll_wildcard_repos = _repos_with_poll_wildcard()
        now = time.time()
        for repo in poll_wildcard_repos:
            disc = _repo_disc.setdefault(repo, {"ts": 0, "etag": None})
            if now - disc["ts"] < DISCOVERY_INTERVAL:
                continue

            changed, new_etag = _check_repo_changed(repo, disc["etag"])
            disc["ts"] = time.time()
            if new_etag:
                disc["etag"] = new_etag

            if not changed:
                log.debug("Repo %s unchanged (304) — skipping PR discovery", repo)
                continue

            pr_numbers = _discover_open_prs(repo)
            log.info("Discovered %d open PRs for %s: %s", len(pr_numbers), repo,
                     pr_numbers[:10])
            with _registry_lock:
                open_set = set(pr_numbers)
                for pr_num in pr_numbers:
                    prkey = _pr_key(repo, pr_num)
                    if prkey not in _pr_state:
                        _pr_state[prkey] = {
                            "repo":         repo,
                            "pr":           pr_num,
                            "_etag":        None,
                            "_head_sha":    None,
                            "_ci_status":   None,
                            "_updated_at":  None,
                            "_last_polled": None,
                        }
                        log.info("Auto-registered PR state for %s#%d (wildcard poll)",
                                 repo, pr_num)

                # Purge _pr_state entries for PRs no longer open and with
                # no direct (non-wildcard) listeners — closed/merged during a gap.
                stale = [
                    pk for pk in list(_pr_state)
                    if _pr_state[pk]["repo"] == repo
                    and _pr_state[pk]["pr"] not in open_set
                    and not _pr_has_direct_listeners(pk)
                ]
                for pk in stale:
                    del _pr_state[pk]
                    log.info("Purged stale PR state for %s (no longer open)", pk)


        # --- Poll registered PRs ---
        pr_states = _get_pr_state_snapshot()

        if not pr_states:
            time.sleep(POLL_INTERVAL)
            continue

        for prkey, state in pr_states.items():
            # Skip if no poll-sourced listeners remain (webhook-only PRs don't need polling)
            with _registry_lock:
                if not _pr_has_poll_listeners(prkey):
                    continue

            try:
                signals = _poll_pr(prkey, state)
                if signals:
                    repo, pr_str = prkey.split("#")
                    for sig in signals:
                        _record("poll_signal", repo, int(pr_str), sig, detail="poller")
                _dispatch_signals(prkey, signals)
            except Exception as e:
                log.error("Error polling %s: %s", prkey, e, exc_info=True)

            time.sleep(2)  # small gap between PRs

        time.sleep(POLL_INTERVAL)


# ---------------------------------------------------------------------------
# HTTP API
# ---------------------------------------------------------------------------

def _json_response(handler: BaseHTTPRequestHandler, code: int, data: dict | list) -> None:
    body = json.dumps(data, indent=2).encode()
    handler.send_response(code)
    handler.send_header("Content-Type", "application/json")
    handler.send_header("Content-Length", str(len(body)))
    handler.end_headers()
    handler.wfile.write(body)


def _html_response(handler: BaseHTTPRequestHandler, code: int, html: str) -> None:
    body = html.encode()
    handler.send_response(code)
    handler.send_header("Content-Type", "text/html; charset=utf-8")
    handler.send_header("Content-Length", str(len(body)))
    handler.end_headers()
    handler.wfile.write(body)


def _render_dashboard() -> str:
    """Render the dashboard HTML with current listener state."""
    with _registry_lock:
        listeners_snapshot = list(_listeners.values())
        n_prs = len(_pr_state)
        pr_state_snapshot = {k: dict(v) for k, v in _pr_state.items()}

    # Sort listeners: wildcards last, then by repo+pr+route
    listeners_snapshot.sort(key=lambda l: (l["repo"], l["pr"], l["route"]))

    def _fmt_ts(ts):
        if ts is None:
            return "—"
        import datetime
        return datetime.datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M:%S")

    def _badge(text, color):
        return f'<span class="badge" style="background:{color}">{text}</span>'

    def _signal_badges(signals):
        colors = {
            "PUSHED": "#2563eb", "OPENED": "#16a34a", "MERGED": "#7c3aed",
            "CLOSED": "#6b7280", "DRAFT": "#92400e", "CI_GREEN": "#15803d",
            "CI_FAILED": "#dc2626", "CI_CANCELLED": "#d97706",
            "NEW_COMMENTS": "#0891b2", "APPROVED": "#059669",
            "CHANGES_REQUESTED": "#b45309", "REVIEW_REQUESTED": "#7c3aed",
            "LABELED": "#9333ea",
        }
        if signals == ["*"]:
            return _badge("*  all", "#374151")
        return " ".join(_badge(s, colors.get(s, "#374151")) for s in signals)

    rows = []
    for l in listeners_snapshot:
        repo = l["repo"]
        pr   = l["pr"]
        route = l["route"]
        pr_display = "wildcard" if pr == 0 else f'<a href="https://github.com/{repo}/pull/{pr}" target="_blank">#{pr}</a>'
        source_badge = _badge(l.get("source", "poll"), "#1d4ed8" if l.get("source") == "poll" else "#7c3aed")
        lkey_js = f"{repo}/{pr}/{route}".replace("'", "\\'")
        pr_js   = str(pr)
        repo_js = repo.replace("'", "\\'")
        route_js = route.replace("'", "\\'")

        prkey = f"{repo}#{pr}"
        ps = pr_state_snapshot.get(prkey, {})
        sha = ps.get("_head_sha")
        sha_display = f'<code title="{sha}">{sha[:8]}</code>' if sha else "—"
        ci = ps.get("_ci_status", "—") or "—"
        ci_color = {"success": "#15803d", "failure": "#dc2626", "pending": "#d97706"}.get(ci, "#6b7280")
        last_polled = _fmt_ts(ps.get("_last_polled"))

        rows.append(f"""
        <tr>
          <td><strong>{repo}</strong></td>
          <td>{pr_display}</td>
          <td><code>{route}</code></td>
          <td>{_signal_badges(l.get("signals", ["*"]))}</td>
          <td>{source_badge}</td>
          <td><code style="font-size:0.8em">{l.get("branch") or "—"}</code></td>
          <td><code style="font-size:0.75em">{l.get("deliver","—")}</code></td>
          <td>{sha_display}</td>
          <td><span style="color:{ci_color};font-weight:600">{ci}</span></td>
          <td>{last_polled}</td>
          <td>{_fmt_ts(l.get("added_at"))}</td>
          <td class="actions">
            <button class="btn btn-fire" onclick="openFireModal('{repo_js}',{pr_js},'{route_js}')">⚡ Fire</button>
            <button class="btn btn-del" onclick="removeListener('{lkey_js}',this)">🗑 Remove</button>
          </td>
        </tr>""")

    rows_html = "\n".join(rows) if rows else '<tr><td colspan="12" style="text-align:center;color:#6b7280;padding:2rem">No listeners registered</td></tr>'

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>PR Gateway Dashboard</title>
  <style>
    *, *::before, *::after {{ box-sizing: border-box; }}
    body {{ font-family: system-ui, -apple-system, sans-serif; margin: 0; background: #0f172a; color: #e2e8f0; }}
    header {{ background: #1e293b; padding: 1rem 2rem; display: flex; align-items: center; gap: 1.5rem; border-bottom: 1px solid #334155; }}
    header h1 {{ margin: 0; font-size: 1.25rem; font-weight: 700; color: #f8fafc; }}
    .stats {{ display: flex; gap: 1.5rem; margin-left: auto; }}
    .stat {{ text-align: center; }}
    .stat .val {{ font-size: 1.5rem; font-weight: 700; color: #38bdf8; }}
    .stat .lbl {{ font-size: 0.7rem; color: #94a3b8; text-transform: uppercase; letter-spacing: .05em; }}
    .tabs {{ display: flex; gap: 0; background: #1e293b; border-bottom: 1px solid #334155; padding: 0 2rem; }}
    .tab {{ padding: 0.6rem 1.25rem; font-size: 0.85rem; font-weight: 600; color: #94a3b8; cursor: pointer; border-bottom: 2px solid transparent; transition: color .15s, border-color .15s; }}
    .tab.active {{ color: #38bdf8; border-bottom-color: #38bdf8; }}
    .tab:hover:not(.active) {{ color: #e2e8f0; }}
    .toolbar {{ padding: 0.75rem 2rem; background: #1e293b; border-bottom: 1px solid #334155; display: flex; gap: 1rem; align-items: center; }}
    .toolbar label {{ font-size: 0.85rem; color: #94a3b8; }}
    .toolbar select {{ background: #0f172a; color: #e2e8f0; border: 1px solid #334155; border-radius: 4px; padding: 2px 6px; font-size: 0.85rem; }}
    main {{ padding: 1.5rem 2rem; overflow-x: auto; }}
    .pane {{ display: none; }}
    .pane.active {{ display: block; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 0.85rem; }}
    th {{ background: #1e293b; color: #94a3b8; text-transform: uppercase; font-size: 0.7rem; letter-spacing: .05em; padding: 0.6rem 0.75rem; text-align: left; border-bottom: 1px solid #334155; white-space: nowrap; }}
    td {{ padding: 0.55rem 0.75rem; border-bottom: 1px solid #1e293b; vertical-align: middle; }}
    tr:hover td {{ background: #1e293b88; }}
    .badge {{ display: inline-block; font-size: 0.68rem; font-weight: 600; padding: 1px 6px; border-radius: 999px; color: #fff; margin: 1px; }}
    code {{ background: #1e293b; border: 1px solid #334155; border-radius: 3px; padding: 1px 5px; font-size: 0.78em; color: #7dd3fc; }}
    .actions {{ display: flex; gap: 0.4rem; }}
    .btn {{ cursor: pointer; border: none; border-radius: 5px; padding: 4px 10px; font-size: 0.78rem; font-weight: 600; transition: opacity .15s; }}
    .btn:hover {{ opacity: 0.8; }}
    .btn-fire {{ background: #1d4ed8; color: #fff; }}
    .btn-del  {{ background: #dc2626; color: #fff; }}
    .btn-sec  {{ background: #334155; color: #e2e8f0; }}
    a {{ color: #38bdf8; text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    /* History filters */
    .hfilters {{ display: flex; gap: .75rem; align-items: center; flex-wrap: wrap; }}
    .hfilters input, .hfilters select {{ background: #0f172a; color: #e2e8f0; border: 1px solid #334155; border-radius: 4px; padding: 3px 8px; font-size: 0.82rem; }}
    .hfilters input {{ width: 180px; }}
    /* Result badges */
    .r-ok         {{ color: #4ade80; }}
    .r-error      {{ color: #f87171; }}
    .r-coalescing {{ color: #facc15; }}
    .r-busy       {{ color: #fb923c; }}
    /* Kind badges */
    .k-webhook_received {{ background: #7c3aed; }}
    .k-poll_signal      {{ background: #1d4ed8; }}
    .k-coalesced        {{ background: #0891b2; }}
    .k-dispatched       {{ background: #15803d; }}
    .k-skipped          {{ background: #6b7280; }}
    /* Modal */
    .modal-bg {{ display:none; position:fixed; inset:0; background:#00000099; z-index:100; align-items:center; justify-content:center; }}
    .modal-bg.open {{ display:flex; }}
    .modal {{ background: #1e293b; border: 1px solid #334155; border-radius: 10px; padding: 1.5rem; min-width: 340px; }}
    .modal h2 {{ margin: 0 0 1rem; font-size: 1rem; color: #f8fafc; }}
    .modal select {{ width:100%; background:#0f172a; color:#e2e8f0; border:1px solid #334155; border-radius:5px; padding:6px 10px; font-size:0.9rem; margin-bottom:1rem; }}
    .modal-actions {{ display:flex; gap:.5rem; justify-content:flex-end; }}
    .btn-cancel {{ background:#334155; color:#e2e8f0; }}
    .toast {{ position:fixed; bottom:1.5rem; right:1.5rem; background:#0f172a; border:1px solid #334155; border-radius:8px; padding:.75rem 1.25rem; font-size:0.85rem; z-index:200; transition:opacity .3s; }}
    .toast.ok  {{ border-color:#15803d; color:#4ade80; }}
    .toast.err {{ border-color:#dc2626; color:#f87171; }}
  </style>
</head>
<body>
<header>
  <h1>⚡ PR Gateway</h1>
  <div class="stats">
    <div class="stat"><div class="val" id="s-listeners">{len(listeners_snapshot)}</div><div class="lbl">Listeners</div></div>
    <div class="stat"><div class="val" id="s-prs">{n_prs}</div><div class="lbl">PRs polled</div></div>
  </div>
</header>
<div class="tabs">
  <div class="tab active" onclick="showTab('listeners',this)">Listeners</div>
  <div class="tab" onclick="showTab('history',this)">History</div>
</div>
<div class="toolbar">
  <label>Auto-refresh:
    <select id="refresh-sel" onchange="setRefresh(this.value)">
      <option value="0">Off</option>
      <option value="15">15 s</option>
      <option value="30" selected>30 s</option>
      <option value="60">60 s</option>
    </select>
  </label>
  <button class="btn btn-fire" style="margin-left:auto" onclick="location.reload()">↺ Refresh now</button>
</div>
<main>
  <!-- Listeners pane -->
  <div class="pane active" id="pane-listeners">
    <table id="tbl">
      <thead><tr>
        <th>Repo</th><th>PR</th><th>Route</th><th>Signals</th>
        <th>Source</th><th>Branch</th><th>Deliver</th>
        <th>Head SHA</th><th>CI</th><th>Last polled</th><th>Registered</th><th>Actions</th>
      </tr></thead>
      <tbody>{rows_html}</tbody>
    </table>
  </div>

  <!-- History pane -->
  <div class="pane" id="pane-history">
    <div class="hfilters" style="margin-bottom:1rem">
      <input id="hf-repo" placeholder="Filter repo…" oninput="filterHistory()">
      <select id="hf-kind" onchange="filterHistory()">
        <option value="">All kinds</option>
        <option value="webhook_received">webhook_received</option>
        <option value="poll_signal">poll_signal</option>
        <option value="coalesced">coalesced</option>
        <option value="dispatched">dispatched</option>
        <option value="skipped">skipped</option>
      </select>
      <select id="hf-result" onchange="filterHistory()">
        <option value="">All results</option>
        <option value="ok">ok</option>
        <option value="error">error</option>
        <option value="coalescing">coalescing</option>
        <option value="busy">busy</option>
      </select>
      <button class="btn btn-sec" onclick="loadHistory()">↺ Reload</button>
    </div>
    <table id="htbl">
      <thead><tr>
        <th>Time</th><th>Kind</th><th>Repo</th><th>PR</th>
        <th>Signal</th><th>Route</th><th>Result</th><th>Detail</th>
      </tr></thead>
      <tbody id="htbl-body"><tr><td colspan="8" style="color:#6b7280;text-align:center;padding:2rem">Loading…</td></tr></tbody>
    </table>
  </div>
</main>

<!-- Fire modal -->
<div class="modal-bg" id="fire-modal">
  <div class="modal">
    <h2>⚡ Fire signal</h2>
    <div style="font-size:.85rem;color:#94a3b8;margin-bottom:.75rem" id="fire-target"></div>
    <select id="fire-signal">
      {''.join(f'<option value="{s}">{s}</option>' for s in sorted(ALL_SIGNALS))}
    </select>
    <div class="modal-actions">
      <button class="btn btn-cancel" onclick="closeModal()">Cancel</button>
      <button class="btn btn-fire" onclick="doFire()">⚡ Fire</button>
    </div>
  </div>
</div>

<script>
var _fireRepo, _firePr, _fireRoute;
var _historyData = [];

// --- Tabs ---
function showTab(name, el) {{
  document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
  document.querySelectorAll('.pane').forEach(p => p.classList.remove('active'));
  el.classList.add('active');
  document.getElementById('pane-' + name).classList.add('active');
  location.hash = name;
  if (name === 'history') loadHistory();
}}

// --- Fire modal ---
function openFireModal(repo, pr, route) {{
  _fireRepo = repo; _firePr = pr; _fireRoute = route;
  document.getElementById('fire-target').textContent = repo + ' #' + pr + ' [' + route + ']';
  document.getElementById('fire-modal').classList.add('open');
}}
function closeModal() {{
  document.getElementById('fire-modal').classList.remove('open');
}}
function doFire() {{
  var sig = document.getElementById('fire-signal').value;
  closeModal();
  fetch('/fire', {{
    method: 'POST',
    headers: {{'Content-Type': 'application/json'}},
    body: JSON.stringify({{repo: _fireRepo, pr: parseInt(_firePr), signal: sig}})
  }}).then(r => r.json()).then(d => {{
    toast(d.ok ? 'Fired ' + sig + ' → ' + _fireRepo + ' #' + _firePr : 'Error: ' + d.error, d.ok);
    if (d.ok) setTimeout(loadHistory, 500);
  }}).catch(e => toast('Request failed: ' + e, false));
}}

// --- Remove listener ---
function removeListener(lkey, btn) {{
  var parts = lkey.split('/');
  var route = parts[parts.length - 1];
  var pr    = parts[parts.length - 2];
  var repo  = parts.slice(0, parts.length - 2).join('/');
  if (!confirm('Remove listener\\n' + repo + ' #' + pr + ' [' + route + '] ?')) return;
  fetch('/watch/' + repo + '/' + pr + '/' + route, {{method: 'DELETE'}})
    .then(r => r.json()).then(d => {{
      if (d.ok) {{ btn.closest('tr').remove(); toast('Removed listener', true); }}
      else toast('Error: ' + d.message, false);
    }}).catch(e => toast('Request failed: ' + e, false));
}}

// --- History ---
var KIND_COLORS = {{
  webhook_received: '#7c3aed', poll_signal: '#1d4ed8',
  coalesced: '#0891b2', dispatched: '#15803d', skipped: '#6b7280'
}};
var SIG_COLORS = {{
  PUSHED:'#2563eb', OPENED:'#16a34a', MERGED:'#7c3aed', CLOSED:'#6b7280',
  DRAFT:'#92400e', CI_GREEN:'#15803d', CI_FAILED:'#dc2626', CI_CANCELLED:'#d97706',
  NEW_COMMENTS:'#0891b2', APPROVED:'#059669', CHANGES_REQUESTED:'#b45309',
  REVIEW_REQUESTED:'#7c3aed', LABELED:'#9333ea'
}};

function fmtTs(ts) {{
  var d = new Date(ts * 1000);
  return d.toLocaleString('sv').replace('T',' ');
}}
function badge(text, color) {{
  return '<span class="badge" style="background:' + (color||'#374151') + '">' + text + '</span>';
}}
function resultHtml(r) {{
  var cls = {{ok:'r-ok',error:'r-error',coalescing:'r-coalescing',busy:'r-busy'}}[r] || '';
  return '<span class="' + cls + '">' + r + '</span>';
}}

function loadHistory() {{
  fetch('/history').then(r => r.json()).then(data => {{
    _historyData = data;
    renderHistory();
  }}).catch(e => console.error('History load failed', e));
}}

function filterHistory() {{ renderHistory(); }}

function renderHistory() {{
  var repo   = document.getElementById('hf-repo').value.trim().toLowerCase();
  var kind   = document.getElementById('hf-kind').value;
  var result = document.getElementById('hf-result').value;
  var rows = _historyData.filter(e =>
    (!repo   || e.repo.toLowerCase().includes(repo)) &&
    (!kind   || e.kind === kind) &&
    (!result || e.result === result)
  );
  var html = rows.length ? rows.map(e =>
    '<tr>' +
    '<td style="white-space:nowrap;font-size:.78rem">' + fmtTs(e.ts) + '</td>' +
    '<td>' + badge(e.kind, KIND_COLORS[e.kind]) + '</td>' +
    '<td><strong>' + e.repo + '</strong></td>' +
    '<td>' + (e.pr === 0 ? 'wildcard' : '<a href="https://github.com/'+e.repo+'/pull/'+e.pr+'" target="_blank">#'+e.pr+'</a>') + '</td>' +
    '<td>' + badge(e.signal, SIG_COLORS[e.signal]) + '</td>' +
    '<td>' + (e.route ? '<code>' + e.route + '</code>' : '—') + '</td>' +
    '<td>' + resultHtml(e.result) + '</td>' +
    '<td style="font-size:.78rem;color:#94a3b8">' + (e.detail||'') + '</td>' +
    '</tr>'
  ).join('') : '<tr><td colspan="8" style="color:#6b7280;text-align:center;padding:2rem">No entries match filters</td></tr>';
  document.getElementById('htbl-body').innerHTML = html;
}}

// --- Toast ---
function toast(msg, ok) {{
  var t = document.createElement('div');
  t.className = 'toast ' + (ok ? 'ok' : 'err');
  t.textContent = msg;
  document.body.appendChild(t);
  setTimeout(() => t.style.opacity = '0', 2500);
  setTimeout(() => t.remove(), 3000);
}}

// --- Auto-refresh ---
var _timer;
function setRefresh(secs) {{
  clearInterval(_timer);
  if (secs > 0) _timer = setInterval(() => location.reload(), secs * 1000);
}}
setRefresh(30);

// Restore active tab from URL hash on load
(function() {{
  var tab = (location.hash || '').replace('#', '');
  if (tab === 'history') {{
    var el = document.querySelector('.tab[onclick*="history"]');
    if (el) showTab('history', el);
  }}
}})();

// Close modal on background click
document.getElementById('fire-modal').addEventListener('click', function(e) {{
  if (e.target === this) closeModal();
}});
</script>
</body>
</html>"""


def _read_body(handler: BaseHTTPRequestHandler) -> Optional[dict]:
    length = int(handler.headers.get("Content-Length", 0))
    if not length:
        return {}
    try:
        return json.loads(handler.rfile.read(length))
    except json.JSONDecodeError:
        return None


def _parse_watch_path(path: str) -> Optional[tuple[str, int, Optional[str]]]:
    """
    Parse DELETE path variants:
      /watch/{owner%2Frepo}/{pr}
      /watch/{owner%2Frepo}/{pr}/{route}
      /watch/{owner}/{repo}/{pr}
      /watch/{owner}/{repo}/{pr}/{route}
    Returns (repo, pr, route_or_None) or None on parse failure.
    """
    # URL-decode the path first so %2F becomes /
    path = unquote(path)
    parts = path.lstrip("/").split("/")
    # parts[0] == "watch", rest are segments
    if not parts or parts[0] != "watch":
        return None
    rest = parts[1:]

    # Now after unquoting, "apache/camel" would have been split already.
    # Possible shapes:
    #   ["owner", "repo", "pr"]           → 3 parts
    #   ["owner", "repo", "pr", "route"]  → 4 parts
    # (The %2F case is now indistinguishable from the / case after unquoting.)
    if len(rest) == 2:
        # /watch/owner%2Frepo/pr — but after unquote owner/repo gets split
        # So this can't happen for the encoded case; only if repo had no slash
        return None
    elif len(rest) == 3:
        repo  = f"{rest[0]}/{rest[1]}"
        pr_s  = rest[2]
        route = None
    elif len(rest) == 4:
        repo  = f"{rest[0]}/{rest[1]}"
        pr_s  = rest[2]
        route = rest[3]
    else:
        return None

    try:
        pr = int(pr_s)
    except ValueError:
        return None
    return repo, pr, route


class GatewayHandler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        log.debug("HTTP: " + fmt, *args)

    def do_GET(self):
        path = urlparse(self.path).path.rstrip("/")

        if path == "/health":
            with _registry_lock:
                n_listeners = len(_listeners)
                n_prs       = len(_pr_state)
            _json_response(self, 200, {
                "status": "ok", "listeners": n_listeners, "prs": n_prs,
            })

        elif path == "/watches":
            _json_response(self, 200, list_watches())

        elif path == "/history":
            _json_response(self, 200, _get_history())

        elif path in ("/ui", ""):
            _html_response(self, 200, _render_dashboard())

        else:
            _json_response(self, 404, {"error": "not found"})

    def do_POST(self):
        path = urlparse(self.path).path.rstrip("/")

        if path == "/watch":
            body = _read_body(self)
            if body is None:
                _json_response(self, 400, {"error": "invalid JSON"})
                return
            ok, msg = add_watch(body)
            _json_response(self, 200 if ok else 400, {"ok": ok, "message": msg})

        elif path == "/fire":
            # POST {"repo": "owner/repo", "pr": 174, "signal": "PUSHED"}
            # Injects a signal directly into the dispatch pipeline — no GitHub webhook needed.
            body = _read_body(self)
            if body is None:
                _json_response(self, 400, {"error": "invalid JSON"})
                return
            repo   = body.get("repo", "").strip()
            pr_raw = body.get("pr")
            signal = body.get("signal", "").strip().upper()
            if not repo or pr_raw is None or not signal:
                _json_response(self, 400, {"error": "repo, pr and signal are required"})
                return
            try:
                pr = int(pr_raw)
            except (TypeError, ValueError):
                _json_response(self, 400, {"error": "pr must be an integer"})
                return
            if signal not in ALL_SIGNALS:
                _json_response(self, 400, {
                    "error": f"Unknown signal '{signal}'. Valid: {sorted(ALL_SIGNALS)}"
                })
                return
            prkey = _pr_key(repo, pr)
            listeners = _get_listeners_for_pr(prkey)
            if not listeners:
                _json_response(self, 404, {"error": f"No listeners for {prkey}"})
                return
            log.info("Manual /fire: %s → %s", signal, prkey)
            _dispatch_signals(prkey, [signal])
            _json_response(self, 200, {
                "ok": True,
                "message": f"Fired {signal} → {prkey} ({len(listeners)} listener(s))",
            })

        elif path == "/repo-secret":
            # POST {"repo": "owner/repo", "secret": "..."}
            body = _read_body(self)
            if body is None:
                _json_response(self, 400, {"error": "invalid JSON"})
                return
            repo   = body.get("repo", "").strip()
            secret = body.get("secret", "").strip()
            if not repo or not secret:
                _json_response(self, 400, {"error": "repo and secret are required"})
                return
            set_repo_secret(repo, secret)
            log.info("Set webhook secret for %s", repo)
            _json_response(self, 200, {"ok": True, "message": f"Secret set for {repo}"})

        else:
            _json_response(self, 404, {"error": "not found"})

    def do_DELETE(self):
        path = urlparse(self.path).path.rstrip("/")
        parsed = _parse_watch_path(path)
        if not parsed:
            _json_response(self, 404, {"error": "not found"})
            return

        repo, pr, route = parsed
        ok, msg = remove_watch(repo, pr, route)
        _json_response(self, 200 if ok else 404, {"ok": ok, "message": msg})


def api_server() -> None:
    server = HTTPServer(("0.0.0.0", API_PORT), GatewayHandler)
    log.info("API server listening on http://0.0.0.0:%d  (LAN accessible)", API_PORT)
    server.serve_forever()


# ---------------------------------------------------------------------------
# GitHub webhook receiver (public port :8646)
# ---------------------------------------------------------------------------

# Map GitHub event+action combos to our signal vocabulary
def _gh_event_to_signals(event: str, payload: dict) -> list[str]:
    """
    Translate a GitHub webhook event+payload into pr-gateway signal(s).
    Returns an empty list if the event is not actionable.
    """
    signals = []
    action  = payload.get("action", "")

    if event == "pull_request":
        if action == "synchronize":
            signals.append("PUSHED")
        elif action in ("opened", "reopened", "ready_for_review"):
            signals.append("OPENED")
        elif action == "closed":
            if payload.get("pull_request", {}).get("merged"):
                signals.append("MERGED")
            else:
                signals.append("CLOSED")
        elif action == "review_requested":
            signals.append("REVIEW_REQUESTED")
        elif action in ("labeled", "unlabeled"):
            signals.append("LABELED")
        elif action in ("converted_to_draft",):
            signals.append("DRAFT")

    elif event == "check_run":
        if action == "completed":
            conclusion = payload.get("check_run", {}).get("conclusion")
            if conclusion == "success":
                signals.append("CI_GREEN")
            elif conclusion in ("failure", "action_required", "timed_out"):
                signals.append("CI_FAILED")
            elif conclusion in ("cancelled", "skipped", "neutral"):
                signals.append("CI_CANCELLED")

    elif event == "check_suite":
        if action == "completed":
            conclusion = payload.get("check_suite", {}).get("conclusion")
            if conclusion == "success":
                signals.append("CI_GREEN")
            elif conclusion in ("failure", "action_required", "timed_out"):
                signals.append("CI_FAILED")
            elif conclusion in ("cancelled", "skipped", "neutral"):
                signals.append("CI_CANCELLED")

    elif event == "pull_request_review":
        state = payload.get("review", {}).get("state", "")
        if action == "submitted":
            if state == "approved":
                signals.append("APPROVED")
            elif state == "changes_requested":
                signals.append("CHANGES_REQUESTED")
            else:
                # Suppress NEW_COMMENTS for bot-generated reviews (anti-loop filter)
                body = payload.get("review", {}).get("body", "") or ""
                if _BOT_WATERMARK not in body:
                    signals.append("NEW_COMMENTS")
        elif action == "dismissed":
            signals.append("NEW_COMMENTS")

    elif event in ("issue_comment", "pull_request_review_comment"):
        # issue_comment: PR comments (GitHub treats them as issue comments)
        # pull_request_review_comment: inline diff comments
        is_pr = (
            "pull_request" in payload.get("issue", {}).get("html_url", "")
            or "pull_request" in payload  # pull_request_review_comment always has it
        )
        if is_pr and action in ("created", "edited"):
            # Suppress NEW_COMMENTS for bot-generated comments (anti-loop filter).
            # The bot watermarks every comment/review it posts; if the body contains
            # that string, the event is our own output and must not re-trigger us.
            comment_body = (
                payload.get("comment", {}).get("body", "")
                or payload.get("review", {}).get("body", "")
                or ""
            )
            if _BOT_WATERMARK not in comment_body:
                signals.append("NEW_COMMENTS")

    elif event == "workflow_run":
        if action == "completed":
            conclusion = payload.get("workflow_run", {}).get("conclusion")
            if conclusion == "success":
                signals.append("CI_GREEN")
            elif conclusion in ("failure", "timed_out", "action_required"):
                signals.append("CI_FAILED")
            elif conclusion in ("cancelled", "skipped", "neutral"):
                signals.append("CI_CANCELLED")

    elif event == "status":
        # Legacy commit status API
        state = payload.get("state", "")
        if state == "success":
            signals.append("CI_GREEN")
        elif state in ("failure", "error"):
            signals.append("CI_FAILED")

    return signals


def _verify_gh_signature(secret: str, body: bytes, sig_header: str) -> bool:
    if not sig_header or not sig_header.startswith("sha256="):
        return False
    expected = "sha256=" + hmac.new(secret.encode(), body, hashlib.sha256).hexdigest()
    return hmac.compare_digest(expected, sig_header)


class GitHubWebhookHandler(BaseHTTPRequestHandler):
    """Handles inbound GitHub webhook events on the public port."""

    def log_message(self, fmt, *args):
        log.debug("GH-webhook: " + fmt, *args)

    def do_POST(self):
        # Path: /github/{owner}/{repo}
        path  = urlparse(self.path).path.rstrip("/")
        parts = path.lstrip("/").split("/")
        # parts: ["github", "owner", "repo"]
        if len(parts) != 3 or parts[0] != "github":
            self._respond(404, {"error": "not found"})
            return

        repo = f"{parts[1]}/{parts[2]}"

        # Read body
        length = int(self.headers.get("Content-Length", 0))
        body   = self.rfile.read(length) if length else b""

        # Validate HMAC — use per-repo secret if configured, else WEBHOOK_SECRET
        sig    = self.headers.get("X-Hub-Signature-256", "")
        secret = _repo_webhook_secret(repo)
        if not _verify_gh_signature(secret, body, sig):
            log.warning("Invalid GitHub signature for %s", repo)
            self._respond(403, {"error": "invalid signature"})
            return

        event = self.headers.get("X-GitHub-Event", "")
        try:
            payload = json.loads(body)
        except json.JSONDecodeError:
            self._respond(400, {"error": "invalid JSON"})
            return

        # Extract PR number from payload
        pr_num = _extract_pr_number(event, payload)
        if pr_num is None:
            # Not a PR-related event we care about — ack and ignore
            self._respond(200, {"ok": True, "message": "ignored"})
            return

        prkey   = _pr_key(repo, pr_num)
        signals = _gh_event_to_signals(event, payload)

        if not signals:
            self._respond(200, {"ok": True, "message": "no actionable signal"})
            return

        log.info("GitHub webhook: %s/%s#%d event=%s → %s",
                 repo, "", pr_num, event, signals)

        # Record inbound webhook event
        for sig in signals:
            _record("webhook_received", repo, pr_num, sig, detail=f"event={event}")

        # Update shared PR state from payload where possible
        _update_pr_state_from_gh(prkey, event, payload)

        # Dispatch to listeners
        _dispatch_signals(prkey, signals)

        self._respond(200, {"ok": True, "signals": signals})

    def do_GET(self):
        path = urlparse(self.path).path.rstrip("/")
        if path == "/health":
            self._respond(200, {"status": "ok", "port": "github-webhook"})
        else:
            self._respond(404, {"error": "not found"})

    def _respond(self, code: int, data: dict) -> None:
        body = json.dumps(data).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


def _extract_pr_number(event: str, payload: dict) -> Optional[int]:
    """Extract the PR number from a GitHub webhook payload."""
    if event == "pull_request":
        return payload.get("pull_request", {}).get("number")
    elif event in ("check_run", "check_suite"):
        # check_run.pull_requests is a list
        prs = payload.get(event.replace("_", "_"), {}).get("pull_requests", [])
        if prs:
            return prs[0].get("number")
        # check_suite may not have PR list — skip
        return None
    elif event == "pull_request_review":
        return payload.get("pull_request", {}).get("number")
    elif event == "issue_comment":
        # Only applicable if it's a PR
        issue = payload.get("issue", {})
        if "pull_request" in issue:
            return issue.get("number")
    return None


def _update_pr_state_from_gh(prkey: str, event: str, payload: dict) -> None:
    """Update cached PR state from the webhook payload where possible."""
    if event == "pull_request":
        pr = payload.get("pull_request", {})
        _update_pr_state(prkey,
            _head_sha=pr.get("head", {}).get("sha"),
            _updated_at=pr.get("updated_at"),
        )


# Per-repo webhook secrets — stored in the registry or defaulting to WEBHOOK_SECRET
_repo_secrets: dict[str, str] = {}
_repo_secrets_lock = threading.Lock()


def set_repo_secret(repo: str, secret: str) -> None:
    with _repo_secrets_lock:
        _repo_secrets[repo] = secret


def _repo_webhook_secret(repo: str) -> str:
    with _repo_secrets_lock:
        return _repo_secrets.get(repo, WEBHOOK_SECRET)


def _load_secrets_from_env() -> None:
    """
    Read WEBHOOK_SECRET_<owner>__<repo> env vars at startup and populate
    the per-repo secret table. Double underscore separates owner from repo.
    Hyphens in names are stored as underscores in the env var name;
    we try both the literal form and the hyphen-restored form.
    """
    prefix = "WEBHOOK_SECRET_"
    for key, val in os.environ.items():
        if key.startswith(prefix) and val:
            repo_raw = key[len(prefix):]
            if "__" not in repo_raw:
                continue
            owner_part, repo_part = repo_raw.split("__", 1)
            # Env vars can't contain hyphens — stored as underscores.
            # Store both forms so we match regardless of whether the repo
            # name has underscores or hyphens.
            for repo in (
                f"{owner_part}/{repo_part}",                          # literal (underscores)
                f"{owner_part}/{repo_part.replace('_', '-')}",        # hyphens restored
            ):
                _repo_secrets[repo] = val
            log.info("Loaded webhook secret for %s (from env)", f"{owner_part}/{repo_part}")


def gh_webhook_server() -> None:
    server = HTTPServer(("0.0.0.0", GH_PORT), GitHubWebhookHandler)
    log.info("GitHub webhook receiver on http://0.0.0.0:%d  (public)", GH_PORT)
    server.serve_forever()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    log.info("pr-gateway starting (api=%d internal, gh-webhook=%d public, hermes=%s)",
             API_PORT, GH_PORT, TARGET_URL)
    PID_FILE.write_text(str(os.getpid()))
    load_registry()
    _load_secrets_from_env()

    # Poller thread
    threading.Thread(target=poller_loop, name="poller", daemon=True).start()

    # GitHub webhook receiver thread (public)
    threading.Thread(target=gh_webhook_server, name="gh-webhook", daemon=True).start()

    # Admin API in main thread (internal only, blocks)
    try:
        api_server()
    except KeyboardInterrupt:
        log.info("Shutting down.")
    finally:
        PID_FILE.unlink(missing_ok=True)


if __name__ == "__main__":
    main()
